name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

      - name: Deploy via Rsync
        run: |
          rsync -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no" /var/www/dev/tictac web@64.23.172.220:/var/www/dev/tictac
