name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: npm install

      # - name: Build application
      #   run: npm run build

      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     known_hosts: "unnecessary"

      # - name: Adding Known Hosts
      #   run: ssh-keyscan -p 22 -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy with rsync
      #   run: rsync -avz --delete --no-perms --chown=web:web --exclude-from=".github/workflows/rsync-excludes.txt" -e 'ssh -p 22' . ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/dev/tictac

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            . ~/.nvm/nvm.sh
            pm2 restart all
