name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: ls -la

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "unnecessary"

      - name: Deploy project with Rsync
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./"
          TARGET: "/var/www/dev"
          REMOTE_HOST: "64.23.172.220"
          REMOTE_USER: "root"
          REMOTE_PORT: "22"
          EXCLUDE: "/node_modules/"
