name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key

      - name: Deploy project with Rsync
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./"
          TARGET: "/var/www/dev"
          REMOTE_HOST: "64.23.172.220"
          REMOTE_USER: "root"
          REMOTE_PORT: "22"
          EXCLUDE: "/node_modules/"
